import type { Status, Quality, Industry, Source } from "./pipeline";

export type Prospect = {
  id: string;
  name: string;
  ownerName?: string;
  industry: Industry;
  city: string;
  phone?: string;
  email?: string;
  website?: string;
  quality: Quality;
  qualityIssues: string[];
  rating?: string;
  reviewCount?: number;
  googlePlaceId?: string;
  address?: string;
  status: Status;
  source: Source;
  channel?: string;
  packageName?: string;
  valueCents?: number;
  lastContactedAt?: string;
  nextFollowUpAt?: string;
  notes?: string;
  createdAt: string;
};

/** Seed data — modeled on the DFW prospects from the existing prospect-bot. */
export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: "p_1",
    name: "Reliable Roofing Co.",
    industry: "Roofing",
    city: "Plano",
    phone: "(214) 555-0142",
    website: "reliable-roofing-tx.com",
    quality: "Outdated",
    qualityIssues: ["Built on Wix", "Copyright date is years old", "No mobile viewport tag"],
    rating: "4.6",
    reviewCount: 87,
    status: "New Lead",
    source: "Google Maps Bot",
    createdAt: "2026-05-20",
  },
  {
    id: "p_2",
    name: "Frisco Pool Builders",
    industry: "Pool Builder",
    city: "Frisco",
    phone: "(972) 555-0188",
    quality: "No Website",
    qualityIssues: ["No website found"],
    rating: "4.9",
    reviewCount: 142,
    status: "New Lead",
    source: "Google Maps Bot",
    valueCents: 250000,
    packageName: "Authority $2500",
    createdAt: "2026-05-21",
  },
  {
    id: "p_3",
    name: "All-Star HVAC",
    industry: "HVAC",
    city: "McKinney",
    phone: "(469) 555-0199",
    email: "owner@allstarhvac.example",
    website: "allstarhvac.example",
    quality: "Terrible",
    qualityIssues: ["No SSL/HTTPS", "Extremely thin content", "No lead capture form"],
    rating: "4.3",
    reviewCount: 53,
    status: "Email Sent",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-22",
    createdAt: "2026-05-18",
  },
  {
    id: "p_4",
    name: "Mesa Verde Landscaping",
    industry: "Landscaping",
    city: "Allen",
    phone: "(214) 555-0212",
    website: "mesaverdescapes.example",
    quality: "Outdated",
    qualityIssues: ["No H1 heading", "No visible phone number"],
    rating: "4.7",
    reviewCount: 91,
    status: "Follow Up 1",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-15",
    nextFollowUpAt: "2026-05-28",
    notes: "Owner Jim seems interested but hasn't replied to first follow-up.",
    createdAt: "2026-05-10",
  },
  {
    id: "p_5",
    name: "Lone Star Fence",
    industry: "Fencing",
    city: "Prosper",
    phone: "(972) 555-0220",
    email: "info@lonestarfence.example",
    website: "lonestarfence.example",
    quality: "Decent",
    qualityIssues: ["Copyright date is years old"],
    rating: "4.5",
    reviewCount: 67,
    status: "Interested",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-23",
    valueCents: 150000,
    packageName: "Growth $1500",
    createdAt: "2026-05-11",
  },
  {
    id: "p_6",
    name: "Glow Med Spa & Wellness",
    industry: "Med Spa",
    city: "Frisco",
    phone: "(469) 555-0244",
    email: "katie@glowmedspa.example",
    website: "glowmedspa.example",
    quality: "Outdated",
    qualityIssues: ["No SSL/HTTPS", "Built on Squarespace"],
    rating: "4.8",
    reviewCount: 312,
    status: "Call Scheduled",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-24",
    nextFollowUpAt: "2026-05-27",
    valueCents: 250000,
    packageName: "Authority $2500",
    notes: "Call scheduled Tuesday 2pm. Katie is the owner and decision maker.",
    createdAt: "2026-05-08",
  },
  {
    id: "p_7",
    name: "TopCut Tree Service",
    industry: "Tree Service",
    city: "Denton",
    phone: "(940) 555-0256",
    website: "topcuttx.example",
    quality: "Terrible",
    qualityIssues: ["No SSL/HTTPS", "No mobile viewport", "Site returns 500 error"],
    rating: "4.4",
    reviewCount: 28,
    status: "Proposal Sent",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-22",
    valueCents: 150000,
    packageName: "Growth $1500",
    createdAt: "2026-05-05",
  },
  {
    id: "p_8",
    name: "Premier Garage Doors",
    industry: "Garage Doors",
    city: "Carrollton",
    phone: "(972) 555-0278",
    email: "tom@premiergaragetx.example",
    website: "premiergaragetx.example",
    quality: "Decent",
    qualityIssues: [],
    rating: "4.7",
    reviewCount: 156,
    status: "Closed Won",
    source: "Referral",
    valueCents: 250000,
    packageName: "Authority $2500",
    createdAt: "2026-04-12",
  },
  {
    id: "p_9",
    name: "AAA Pest Solutions",
    industry: "Pest Control",
    city: "Richardson",
    phone: "(214) 555-0290",
    quality: "No Website",
    qualityIssues: ["No website found"],
    rating: "4.6",
    reviewCount: 74,
    status: "New Lead",
    source: "Google Maps Bot",
    createdAt: "2026-05-25",
  },
  {
    id: "p_10",
    name: "Bright Smile Dental",
    industry: "Dentist",
    city: "Plano",
    phone: "(972) 555-0301",
    email: "frontdesk@brightsmiletx.example",
    website: "brightsmiletx.example",
    quality: "Outdated",
    qualityIssues: ["No mobile viewport", "Built on Weebly"],
    rating: "4.9",
    reviewCount: 423,
    status: "DM Sent",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-23",
    createdAt: "2026-05-17",
  },
  {
    id: "p_11",
    name: "Capital Concrete & Driveways",
    industry: "Concrete",
    city: "Garland",
    phone: "(214) 555-0322",
    website: "capitalconcrete-tx.example",
    quality: "Terrible",
    qualityIssues: ["Site failed to load", "No phone number visible"],
    rating: "4.2",
    reviewCount: 41,
    status: "New Lead",
    source: "Google Maps Bot",
    createdAt: "2026-05-25",
  },
  {
    id: "p_12",
    name: "Sunset Auto Detail",
    industry: "Auto Detailing",
    city: "The Colony",
    phone: "(469) 555-0344",
    website: "sunsetdetail.example",
    quality: "Outdated",
    qualityIssues: ["No SSL/HTTPS", "Extremely thin content"],
    rating: "4.8",
    reviewCount: 198,
    status: "Follow Up 2",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-10",
    nextFollowUpAt: "2026-05-26",
    notes: "Sent two follow-ups, no response. Trying breakup email next.",
    createdAt: "2026-04-28",
  },
  {
    id: "p_13",
    name: "ProPaint Interior & Exterior",
    industry: "Painting",
    city: "Lewisville",
    phone: "(972) 555-0366",
    email: "mark@propainttx.example",
    quality: "No Website",
    qualityIssues: ["No website found"],
    rating: "4.7",
    reviewCount: 112,
    status: "Email Sent",
    source: "Google Maps Bot",
    lastContactedAt: "2026-05-24",
    createdAt: "2026-05-19",
  },
  {
    id: "p_14",
    name: "Spark Electric LLC",
    industry: "Electrical",
    city: "Flower Mound",
    phone: "(214) 555-0388",
    website: "sparkelectricllc.example",
    quality: "Decent",
    qualityIssues: ["No meta description"],
    rating: "4.5",
    reviewCount: 89,
    status: "Closed Lost",
    source: "Google Maps Bot",
    notes: "Owner said they already have an agency.",
    createdAt: "2026-04-18",
  },
];
